<?php

namespace ContainerB2fxjsJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllercheckService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NxgfFSG.App\Controller\SecurityController::check()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NxgfFSG.App\\Controller\\SecurityController::check()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'apiService' => ['privates', 'App\\Service\\ApiService', 'getApiServiceService', true],
        ], [
            'apiService' => 'App\\Service\\ApiService',
        ]))->withContext('App\\Controller\\SecurityController::check()', $container);
    }
}
