<?php

namespace ContainerK44cPci;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6_D3RwPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6.d3RwP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6.d3RwP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\GoogleController::connectAction' => ['privates', '.service_locator.wLvy5Az.App\\Controller\\GoogleController::connectAction()', 'getGoogleControllerconnectActionService', true],
            'App\\Controller\\GoogleController::connectCheckAction' => ['privates', '.service_locator.wLvy5Az.App\\Controller\\GoogleController::connectCheckAction()', 'getGoogleControllerconnectCheckActionService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController::check' => ['privates', '.service_locator.NxgfFSG.App\\Controller\\SecurityController::check()', 'getSecurityControllercheckService', true],
            'App\\Controller\\SettingsController::budgetAlert' => ['privates', '.service_locator.NxgfFSG.App\\Controller\\SettingsController::budgetAlert()', 'getSettingsControllerbudgetAlertService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\GoogleController:connectAction' => ['privates', '.service_locator.wLvy5Az.App\\Controller\\GoogleController::connectAction()', 'getGoogleControllerconnectActionService', true],
            'App\\Controller\\GoogleController:connectCheckAction' => ['privates', '.service_locator.wLvy5Az.App\\Controller\\GoogleController::connectCheckAction()', 'getGoogleControllerconnectCheckActionService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SecurityController:check' => ['privates', '.service_locator.NxgfFSG.App\\Controller\\SecurityController::check()', 'getSecurityControllercheckService', true],
            'App\\Controller\\SettingsController:budgetAlert' => ['privates', '.service_locator.NxgfFSG.App\\Controller\\SettingsController::budgetAlert()', 'getSettingsControllerbudgetAlertService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\GoogleController::connectAction' => '?',
            'App\\Controller\\GoogleController::connectCheckAction' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::check' => '?',
            'App\\Controller\\SettingsController::budgetAlert' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\GoogleController:connectAction' => '?',
            'App\\Controller\\GoogleController:connectCheckAction' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:check' => '?',
            'App\\Controller\\SettingsController:budgetAlert' => '?',
        ]);
    }
}
