<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSRGB2A8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSRGB2A8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSRGB2A8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSRGB2A8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSRGB2A8\App_KernelDevDebugContainer([
    'container.build_hash' => 'SRGB2A8',
    'container.build_id' => 'ced2ba9e',
    'container.build_time' => 1742988838,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSRGB2A8');
