<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK44cPci\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK44cPci/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK44cPci.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK44cPci\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK44cPci\App_KernelDevDebugContainer([
    'container.build_hash' => 'K44cPci',
    'container.build_id' => '9ebf2e71',
    'container.build_time' => 1743056473,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK44cPci');
